version: "3.9"

networks:
  microservices-net:
    external: true

services:
  postgres:
    image: postgres:16-alpine
    container_name: database-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: database_service
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "127.0.0.1:5433:5432"
    volumes:
      - diaxel_postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d database_service"]
      interval: 3s
      timeout: 3s
      retries: 5
    networks:
      - microservices-net

  database-service:
    build: ./database-service
    container_name: database-service
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - "50051:50051"
    env_file:
      - ./database-service/.env
    restart: unless-stopped
    networks:
      - microservices-net

  auth-service:
    build: ./auth-service
    container_name: auth-service
    ports:
      - "8082:8080"
    depends_on:
      - database-service
    env_file:
      - ./auth-service/.env
    restart: unless-stopped
    networks:
      - microservices-net

  ai-service:
    build: ./ai-service
    container_name: ai-service
    ports:
      - "8081:8080"
    depends_on:
      - database-service
    env_file:
      - ./ai-service/.env
    restart: unless-stopped
    networks:
      - microservices-net

  api-gateway:
    build: ./api-gateway
    container_name: api-gateway-service
    ports:
      - "8085:8080"
    depends_on:
      - database-service
      - auth-service
      - ai-service
    env_file:
      - ./api-gateway/.env
    restart: unless-stopped
    networks:
      - microservices-net

volumes:
  diaxel_postgres_data:
    name: database-service_diaxel_postgres_data
