version: "3.9"

networks:
  microservices-net-v2:
    external: true

services:
  postgres-v2:
    image: postgres:16-alpine
    container_name: database-postgres-v2
    restart: unless-stopped
    environment:
      POSTGRES_DB: database_service
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "127.0.0.1:5434:5432"
    volumes:
      - diaxel_postgres_data_v2:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d database_service"]
      interval: 3s
      timeout: 3s
      retries: 5
    networks:
      - microservices-net-v2

  database-service-v2:
    image: diaxel-database-service-v2
    build: ./database-service
    container_name: database-service-v2
    depends_on:
      postgres-v2:
        condition: service_healthy
    ports:
      - "50052:50051"
    env_file:
      - ./database-service/.env
    restart: unless-stopped
    networks:
      - microservices-net-v2

  auth-service-v2:
    image: diaxel-auth-service-v2
    build: ./auth-service
    container_name: auth-service-v2
    ports:
      - "8092:8080"
    depends_on:
      - database-service-v2
    env_file:
      - ./auth-service/.env
    restart: unless-stopped
    networks:
      - microservices-net-v2

  ai-service-v2:
    image: diaxel-ai-service-v2
    build: ./ai-service
    container_name: ai-service-v2
    ports:
      - "8091:8080"
    depends_on:
      - database-service-v2
    env_file:
      - ./ai-service/.env
    restart: unless-stopped
    networks:
      - microservices-net-v2

  api-gateway-v2:
    image: diaxel-api-gateway-v2
    build: ./api-gateway
    container_name: api-gateway-service-v2
    ports:
      - "8095:8080"
    depends_on:
      - database-service-v2
      - auth-service-v2
      - ai-service-v2
    env_file:
      - ./api-gateway/.env
    restart: unless-stopped
    networks:
      - microservices-net-v2

volumes:
  diaxel_postgres_data_v2:
    name: database-service_diaxel_postgres_data_v2
