version: "3.9"

services:
  app-v2:
    image: diaxel-ai-service-v2
    build: .
    container_name: ai-service-v2
    ports:
      - "8091:8080"
    restart: unless-stopped
    env_file:
      - .env
    networks:
      - microservices-net-v2

networks:
  microservices-net-v2:
    external: true