version: "3.9"

services:
  database-service:
    build: .
    container_name: database-service-v2
    networks:
      - microservices-net-v2
    restart: unless-stopped
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      POSTGRES_HOST: database-postgres-v2
      POSTGRES_PORT: 5432
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: database_service

  postgres:
    image: postgres:16-alpine
    container_name: database-postgres-v2
    networks:
      - microservices-net-v2
    restart: unless-stopped
    environment:
      POSTGRES_DB: database_service
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "127.0.0.1:5434:5432"
    volumes:
      - diaxel_postgres_data_v2:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d database_service"]
      interval: 3s
      timeout: 3s
      retries: 5

volumes:
  diaxel_postgres_data_v2:

networks:
  microservices-net-v2:
    external: true