version: "3.9"

services:
  app:
    image: diaxel-auth-service-v2
    build: .
    container_name: auth-service-v2
    ports:
      - "8092:8080"
    restart: unless-stopped
    env_file:
      - .env
    networks:
      - microservices-net-v2

networks:
  microservices-net-v2:
    external: true