// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.28.3
// source: database.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AnalyticsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AssistantId   string                 `protobuf:"bytes,1,opt,name=assistant_id,json=assistantId,proto3" json:"assistant_id,omitempty"`
	Platform      string                 `protobuf:"bytes,2,opt,name=platform,proto3" json:"platform,omitempty"`
	StartDate     string                 `protobuf:"bytes,3,opt,name=start_date,json=startDate,proto3" json:"start_date,omitempty"`
	EndDate       string                 `protobuf:"bytes,4,opt,name=end_date,json=endDate,proto3" json:"end_date,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AnalyticsRequest) Reset() {
	*x = AnalyticsRequest{}
	mi := &file_database_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AnalyticsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AnalyticsRequest) ProtoMessage() {}

func (x *AnalyticsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_database_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AnalyticsRequest.ProtoReflect.Descriptor instead.
func (*AnalyticsRequest) Descriptor() ([]byte, []int) {
	return file_database_proto_rawDescGZIP(), []int{0}
}

func (x *AnalyticsRequest) GetAssistantId() string {
	if x != nil {
		return x.AssistantId
	}
	return ""
}

func (x *AnalyticsRequest) GetPlatform() string {
	if x != nil {
		return x.Platform
	}
	return ""
}

func (x *AnalyticsRequest) GetStartDate() string {
	if x != nil {
		return x.StartDate
	}
	return ""
}

func (x *AnalyticsRequest) GetEndDate() string {
	if x != nil {
		return x.EndDate
	}
	return ""
}

type AnalyticsByAssistantRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AssistantId   string                 `protobuf:"bytes,1,opt,name=assistant_id,json=assistantId,proto3" json:"assistant_id,omitempty"`
	Platform      string                 `protobuf:"bytes,2,opt,name=platform,proto3" json:"platform,omitempty"`
	StartDate     string                 `protobuf:"bytes,3,opt,name=start_date,json=startDate,proto3" json:"start_date,omitempty"`
	EndDate       string                 `protobuf:"bytes,4,opt,name=end_date,json=endDate,proto3" json:"end_date,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AnalyticsByAssistantRequest) Reset() {
	*x = AnalyticsByAssistantRequest{}
	mi := &file_database_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AnalyticsByAssistantRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AnalyticsByAssistantRequest) ProtoMessage() {}

func (x *AnalyticsByAssistantRequest) ProtoReflect() protoreflect.Message {
	mi := &file_database_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AnalyticsByAssistantRequest.ProtoReflect.Descriptor instead.
func (*AnalyticsByAssistantRequest) Descriptor() ([]byte, []int) {
	return file_database_proto_rawDescGZIP(), []int{1}
}

func (x *AnalyticsByAssistantRequest) GetAssistantId() string {
	if x != nil {
		return x.AssistantId
	}
	return ""
}

func (x *AnalyticsByAssistantRequest) GetPlatform() string {
	if x != nil {
		return x.Platform
	}
	return ""
}

func (x *AnalyticsByAssistantRequest) GetStartDate() string {
	if x != nil {
		return x.StartDate
	}
	return ""
}

func (x *AnalyticsByAssistantRequest) GetEndDate() string {
	if x != nil {
		return x.EndDate
	}
	return ""
}

type AnalyticsResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	AssistantId    string                 `protobuf:"bytes,1,opt,name=assistant_id,json=assistantId,proto3" json:"assistant_id,omitempty"`
	TotalChats     int32                  `protobuf:"varint,2,opt,name=total_chats,json=totalChats,proto3" json:"total_chats,omitempty"`
	ActiveUsers    int32                  `protobuf:"varint,3,opt,name=active_users,json=activeUsers,proto3" json:"active_users,omitempty"`
	EngagementRate float64                `protobuf:"fixed64,4,opt,name=engagement_rate,json=engagementRate,proto3" json:"engagement_rate,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *AnalyticsResponse) Reset() {
	*x = AnalyticsResponse{}
	mi := &file_database_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AnalyticsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AnalyticsResponse) ProtoMessage() {}

func (x *AnalyticsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_database_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AnalyticsResponse.ProtoReflect.Descriptor instead.
func (*AnalyticsResponse) Descriptor() ([]byte, []int) {
	return file_database_proto_rawDescGZIP(), []int{2}
}

func (x *AnalyticsResponse) GetAssistantId() string {
	if x != nil {
		return x.AssistantId
	}
	return ""
}

func (x *AnalyticsResponse) GetTotalChats() int32 {
	if x != nil {
		return x.TotalChats
	}
	return 0
}

func (x *AnalyticsResponse) GetActiveUsers() int32 {
	if x != nil {
		return x.ActiveUsers
	}
	return 0
}

func (x *AnalyticsResponse) GetEngagementRate() float64 {
	if x != nil {
		return x.EngagementRate
	}
	return 0
}

type CreateUserRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Email         string                 `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	PasswordHash  string                 `protobuf:"bytes,2,opt,name=password_hash,json=passwordHash,proto3" json:"password_hash,omitempty"`
	Role          string                 `protobuf:"bytes,3,opt,name=role,proto3" json:"role,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateUserRequest) Reset() {
	*x = CreateUserRequest{}
	mi := &file_database_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateUserRequest) ProtoMessage() {}

func (x *CreateUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_database_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateUserRequest.ProtoReflect.Descriptor instead.
func (*CreateUserRequest) Descriptor() ([]byte, []int) {
	return file_database_proto_rawDescGZIP(), []int{3}
}

func (x *CreateUserRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *CreateUserRequest) GetPasswordHash() string {
	if x != nil {
		return x.PasswordHash
	}
	return ""
}

func (x *CreateUserRequest) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

type GetUserRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserRequest) Reset() {
	*x = GetUserRequest{}
	mi := &file_database_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserRequest) ProtoMessage() {}

func (x *GetUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_database_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserRequest.ProtoReflect.Descriptor instead.
func (*GetUserRequest) Descriptor() ([]byte, []int) {
	return file_database_proto_rawDescGZIP(), []int{4}
}

func (x *GetUserRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type UserResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Email         string                 `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	PasswordHash  string                 `protobuf:"bytes,3,opt,name=password_hash,json=passwordHash,proto3" json:"password_hash,omitempty"`
	Role          string                 `protobuf:"bytes,4,opt,name=role,proto3" json:"role,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserResponse) Reset() {
	*x = UserResponse{}
	mi := &file_database_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserResponse) ProtoMessage() {}

func (x *UserResponse) ProtoReflect() protoreflect.Message {
	mi := &file_database_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserResponse.ProtoReflect.Descriptor instead.
func (*UserResponse) Descriptor() ([]byte, []int) {
	return file_database_proto_rawDescGZIP(), []int{5}
}

func (x *UserResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UserResponse) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *UserResponse) GetPasswordHash() string {
	if x != nil {
		return x.PasswordHash
	}
	return ""
}

func (x *UserResponse) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

func (x *UserResponse) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

type SaveRefreshTokenRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	TokenHash     string                 `protobuf:"bytes,2,opt,name=token_hash,json=tokenHash,proto3" json:"token_hash,omitempty"`
	ExpiresAt     string                 `protobuf:"bytes,3,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SaveRefreshTokenRequest) Reset() {
	*x = SaveRefreshTokenRequest{}
	mi := &file_database_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SaveRefreshTokenRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SaveRefreshTokenRequest) ProtoMessage() {}

func (x *SaveRefreshTokenRequest) ProtoReflect() protoreflect.Message {
	mi := &file_database_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SaveRefreshTokenRequest.ProtoReflect.Descriptor instead.
func (*SaveRefreshTokenRequest) Descriptor() ([]byte, []int) {
	return file_database_proto_rawDescGZIP(), []int{6}
}

func (x *SaveRefreshTokenRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *SaveRefreshTokenRequest) GetTokenHash() string {
	if x != nil {
		return x.TokenHash
	}
	return ""
}

func (x *SaveRefreshTokenRequest) GetExpiresAt() string {
	if x != nil {
		return x.ExpiresAt
	}
	return ""
}

type SaveRefreshTokenResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SaveRefreshTokenResponse) Reset() {
	*x = SaveRefreshTokenResponse{}
	mi := &file_database_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SaveRefreshTokenResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SaveRefreshTokenResponse) ProtoMessage() {}

func (x *SaveRefreshTokenResponse) ProtoReflect() protoreflect.Message {
	mi := &file_database_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SaveRefreshTokenResponse.ProtoReflect.Descriptor instead.
func (*SaveRefreshTokenResponse) Descriptor() ([]byte, []int) {
	return file_database_proto_rawDescGZIP(), []int{7}
}

func (x *SaveRefreshTokenResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type GetRefreshTokenRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TokenHash     string                 `protobuf:"bytes,1,opt,name=token_hash,json=tokenHash,proto3" json:"token_hash,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRefreshTokenRequest) Reset() {
	*x = GetRefreshTokenRequest{}
	mi := &file_database_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRefreshTokenRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRefreshTokenRequest) ProtoMessage() {}

func (x *GetRefreshTokenRequest) ProtoReflect() protoreflect.Message {
	mi := &file_database_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRefreshTokenRequest.ProtoReflect.Descriptor instead.
func (*GetRefreshTokenRequest) Descriptor() ([]byte, []int) {
	return file_database_proto_rawDescGZIP(), []int{8}
}

func (x *GetRefreshTokenRequest) GetTokenHash() string {
	if x != nil {
		return x.TokenHash
	}
	return ""
}

type RefreshTokenResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	TokenHash     string                 `protobuf:"bytes,3,opt,name=token_hash,json=tokenHash,proto3" json:"token_hash,omitempty"`
	ExpiresAt     string                 `protobuf:"bytes,4,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RefreshTokenResponse) Reset() {
	*x = RefreshTokenResponse{}
	mi := &file_database_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RefreshTokenResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RefreshTokenResponse) ProtoMessage() {}

func (x *RefreshTokenResponse) ProtoReflect() protoreflect.Message {
	mi := &file_database_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RefreshTokenResponse.ProtoReflect.Descriptor instead.
func (*RefreshTokenResponse) Descriptor() ([]byte, []int) {
	return file_database_proto_rawDescGZIP(), []int{9}
}

func (x *RefreshTokenResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *RefreshTokenResponse) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *RefreshTokenResponse) GetTokenHash() string {
	if x != nil {
		return x.TokenHash
	}
	return ""
}

func (x *RefreshTokenResponse) GetExpiresAt() string {
	if x != nil {
		return x.ExpiresAt
	}
	return ""
}

func (x *RefreshTokenResponse) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

type DeleteRefreshTokenRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TokenHash     string                 `protobuf:"bytes,1,opt,name=token_hash,json=tokenHash,proto3" json:"token_hash,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteRefreshTokenRequest) Reset() {
	*x = DeleteRefreshTokenRequest{}
	mi := &file_database_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteRefreshTokenRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteRefreshTokenRequest) ProtoMessage() {}

func (x *DeleteRefreshTokenRequest) ProtoReflect() protoreflect.Message {
	mi := &file_database_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteRefreshTokenRequest.ProtoReflect.Descriptor instead.
func (*DeleteRefreshTokenRequest) Descriptor() ([]byte, []int) {
	return file_database_proto_rawDescGZIP(), []int{10}
}

func (x *DeleteRefreshTokenRequest) GetTokenHash() string {
	if x != nil {
		return x.TokenHash
	}
	return ""
}

type DeleteRefreshTokenResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteRefreshTokenResponse) Reset() {
	*x = DeleteRefreshTokenResponse{}
	mi := &file_database_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteRefreshTokenResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteRefreshTokenResponse) ProtoMessage() {}

func (x *DeleteRefreshTokenResponse) ProtoReflect() protoreflect.Message {
	mi := &file_database_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteRefreshTokenResponse.ProtoReflect.Descriptor instead.
func (*DeleteRefreshTokenResponse) Descriptor() ([]byte, []int) {
	return file_database_proto_rawDescGZIP(), []int{11}
}

func (x *DeleteRefreshTokenResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type CreateChatRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AssistantId   string                 `protobuf:"bytes,1,opt,name=assistant_id,json=assistantId,proto3" json:"assistant_id,omitempty"`
	CustomerId    string                 `protobuf:"bytes,2,opt,name=customer_id,json=customerId,proto3" json:"customer_id,omitempty"`
	Platform      string                 `protobuf:"bytes,3,opt,name=platform,proto3" json:"platform,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateChatRequest) Reset() {
	*x = CreateChatRequest{}
	mi := &file_database_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateChatRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateChatRequest) ProtoMessage() {}

func (x *CreateChatRequest) ProtoReflect() protoreflect.Message {
	mi := &file_database_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateChatRequest.ProtoReflect.Descriptor instead.
func (*CreateChatRequest) Descriptor() ([]byte, []int) {
	return file_database_proto_rawDescGZIP(), []int{12}
}

func (x *CreateChatRequest) GetAssistantId() string {
	if x != nil {
		return x.AssistantId
	}
	return ""
}

func (x *CreateChatRequest) GetCustomerId() string {
	if x != nil {
		return x.CustomerId
	}
	return ""
}

func (x *CreateChatRequest) GetPlatform() string {
	if x != nil {
		return x.Platform
	}
	return ""
}

type ChatResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	AssistantId   string                 `protobuf:"bytes,2,opt,name=assistant_id,json=assistantId,proto3" json:"assistant_id,omitempty"`
	CustomerId    string                 `protobuf:"bytes,3,opt,name=customer_id,json=customerId,proto3" json:"customer_id,omitempty"`
	Platform      string                 `protobuf:"bytes,4,opt,name=platform,proto3" json:"platform,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     string                 `protobuf:"bytes,6,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	MessageCount  int32                  `protobuf:"varint,7,opt,name=message_count,json=messageCount,proto3" json:"message_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChatResponse) Reset() {
	*x = ChatResponse{}
	mi := &file_database_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChatResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatResponse) ProtoMessage() {}

func (x *ChatResponse) ProtoReflect() protoreflect.Message {
	mi := &file_database_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChatResponse.ProtoReflect.Descriptor instead.
func (*ChatResponse) Descriptor() ([]byte, []int) {
	return file_database_proto_rawDescGZIP(), []int{13}
}

func (x *ChatResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ChatResponse) GetAssistantId() string {
	if x != nil {
		return x.AssistantId
	}
	return ""
}

func (x *ChatResponse) GetCustomerId() string {
	if x != nil {
		return x.CustomerId
	}
	return ""
}

func (x *ChatResponse) GetPlatform() string {
	if x != nil {
		return x.Platform
	}
	return ""
}

func (x *ChatResponse) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *ChatResponse) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

func (x *ChatResponse) GetMessageCount() int32 {
	if x != nil {
		return x.MessageCount
	}
	return 0
}

type SaveMessageRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ChatId        string                 `protobuf:"bytes,1,opt,name=chat_id,json=chatId,proto3" json:"chat_id,omitempty"`
	Role          string                 `protobuf:"bytes,2,opt,name=role,proto3" json:"role,omitempty"`
	Content       string                 `protobuf:"bytes,3,opt,name=content,proto3" json:"content,omitempty"`
	Platform      string                 `protobuf:"bytes,4,opt,name=platform,proto3" json:"platform,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SaveMessageRequest) Reset() {
	*x = SaveMessageRequest{}
	mi := &file_database_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SaveMessageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SaveMessageRequest) ProtoMessage() {}

func (x *SaveMessageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_database_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SaveMessageRequest.ProtoReflect.Descriptor instead.
func (*SaveMessageRequest) Descriptor() ([]byte, []int) {
	return file_database_proto_rawDescGZIP(), []int{14}
}

func (x *SaveMessageRequest) GetChatId() string {
	if x != nil {
		return x.ChatId
	}
	return ""
}

func (x *SaveMessageRequest) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

func (x *SaveMessageRequest) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *SaveMessageRequest) GetPlatform() string {
	if x != nil {
		return x.Platform
	}
	return ""
}

type MessageResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	ChatId        string                 `protobuf:"bytes,2,opt,name=chat_id,json=chatId,proto3" json:"chat_id,omitempty"`
	Role          string                 `protobuf:"bytes,3,opt,name=role,proto3" json:"role,omitempty"`
	Content       string                 `protobuf:"bytes,4,opt,name=content,proto3" json:"content,omitempty"`
	Platform      string                 `protobuf:"bytes,5,opt,name=platform,proto3" json:"platform,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,6,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MessageResponse) Reset() {
	*x = MessageResponse{}
	mi := &file_database_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MessageResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MessageResponse) ProtoMessage() {}

func (x *MessageResponse) ProtoReflect() protoreflect.Message {
	mi := &file_database_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MessageResponse.ProtoReflect.Descriptor instead.
func (*MessageResponse) Descriptor() ([]byte, []int) {
	return file_database_proto_rawDescGZIP(), []int{15}
}

func (x *MessageResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *MessageResponse) GetChatId() string {
	if x != nil {
		return x.ChatId
	}
	return ""
}

func (x *MessageResponse) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

func (x *MessageResponse) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *MessageResponse) GetPlatform() string {
	if x != nil {
		return x.Platform
	}
	return ""
}

func (x *MessageResponse) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

type GetChatMessagesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ChatId        string                 `protobuf:"bytes,1,opt,name=chat_id,json=chatId,proto3" json:"chat_id,omitempty"`
	Limit         int32                  `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	Offset        int32                  `protobuf:"varint,3,opt,name=offset,proto3" json:"offset,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetChatMessagesRequest) Reset() {
	*x = GetChatMessagesRequest{}
	mi := &file_database_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetChatMessagesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetChatMessagesRequest) ProtoMessage() {}

func (x *GetChatMessagesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_database_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetChatMessagesRequest.ProtoReflect.Descriptor instead.
func (*GetChatMessagesRequest) Descriptor() ([]byte, []int) {
	return file_database_proto_rawDescGZIP(), []int{16}
}

func (x *GetChatMessagesRequest) GetChatId() string {
	if x != nil {
		return x.ChatId
	}
	return ""
}

func (x *GetChatMessagesRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *GetChatMessagesRequest) GetOffset() int32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

type GetAllChatMessagesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ChatId        string                 `protobuf:"bytes,1,opt,name=chat_id,json=chatId,proto3" json:"chat_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAllChatMessagesRequest) Reset() {
	*x = GetAllChatMessagesRequest{}
	mi := &file_database_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAllChatMessagesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAllChatMessagesRequest) ProtoMessage() {}

func (x *GetAllChatMessagesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_database_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAllChatMessagesRequest.ProtoReflect.Descriptor instead.
func (*GetAllChatMessagesRequest) Descriptor() ([]byte, []int) {
	return file_database_proto_rawDescGZIP(), []int{17}
}

func (x *GetAllChatMessagesRequest) GetChatId() string {
	if x != nil {
		return x.ChatId
	}
	return ""
}

type MessagesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Messages      []*MessageResponse     `protobuf:"bytes,1,rep,name=messages,proto3" json:"messages,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MessagesResponse) Reset() {
	*x = MessagesResponse{}
	mi := &file_database_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MessagesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MessagesResponse) ProtoMessage() {}

func (x *MessagesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_database_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MessagesResponse.ProtoReflect.Descriptor instead.
func (*MessagesResponse) Descriptor() ([]byte, []int) {
	return file_database_proto_rawDescGZIP(), []int{18}
}

func (x *MessagesResponse) GetMessages() []*MessageResponse {
	if x != nil {
		return x.Messages
	}
	return nil
}

type GetUserByEmailRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Email         string                 `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserByEmailRequest) Reset() {
	*x = GetUserByEmailRequest{}
	mi := &file_database_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserByEmailRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserByEmailRequest) ProtoMessage() {}

func (x *GetUserByEmailRequest) ProtoReflect() protoreflect.Message {
	mi := &file_database_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserByEmailRequest.ProtoReflect.Descriptor instead.
func (*GetUserByEmailRequest) Descriptor() ([]byte, []int) {
	return file_database_proto_rawDescGZIP(), []int{19}
}

func (x *GetUserByEmailRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

type UpdateUserRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Email         string                 `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	PasswordHash  string                 `protobuf:"bytes,3,opt,name=password_hash,json=passwordHash,proto3" json:"password_hash,omitempty"`
	Role          string                 `protobuf:"bytes,4,opt,name=role,proto3" json:"role,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateUserRequest) Reset() {
	*x = UpdateUserRequest{}
	mi := &file_database_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateUserRequest) ProtoMessage() {}

func (x *UpdateUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_database_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateUserRequest.ProtoReflect.Descriptor instead.
func (*UpdateUserRequest) Descriptor() ([]byte, []int) {
	return file_database_proto_rawDescGZIP(), []int{20}
}

func (x *UpdateUserRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdateUserRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *UpdateUserRequest) GetPasswordHash() string {
	if x != nil {
		return x.PasswordHash
	}
	return ""
}

func (x *UpdateUserRequest) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

type DeleteUserRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteUserRequest) Reset() {
	*x = DeleteUserRequest{}
	mi := &file_database_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteUserRequest) ProtoMessage() {}

func (x *DeleteUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_database_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteUserRequest.ProtoReflect.Descriptor instead.
func (*DeleteUserRequest) Descriptor() ([]byte, []int) {
	return file_database_proto_rawDescGZIP(), []int{21}
}

func (x *DeleteUserRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type DeleteUserResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteUserResponse) Reset() {
	*x = DeleteUserResponse{}
	mi := &file_database_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteUserResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteUserResponse) ProtoMessage() {}

func (x *DeleteUserResponse) ProtoReflect() protoreflect.Message {
	mi := &file_database_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteUserResponse.ProtoReflect.Descriptor instead.
func (*DeleteUserResponse) Descriptor() ([]byte, []int) {
	return file_database_proto_rawDescGZIP(), []int{22}
}

func (x *DeleteUserResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type GetChatRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetChatRequest) Reset() {
	*x = GetChatRequest{}
	mi := &file_database_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetChatRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetChatRequest) ProtoMessage() {}

func (x *GetChatRequest) ProtoReflect() protoreflect.Message {
	mi := &file_database_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetChatRequest.ProtoReflect.Descriptor instead.
func (*GetChatRequest) Descriptor() ([]byte, []int) {
	return file_database_proto_rawDescGZIP(), []int{23}
}

func (x *GetChatRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetChatsByUserRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	AssistantId   string                 `protobuf:"bytes,2,opt,name=assistant_id,json=assistantId,proto3" json:"assistant_id,omitempty"`
	Limit         int32                  `protobuf:"varint,3,opt,name=limit,proto3" json:"limit,omitempty"`
	Offset        int32                  `protobuf:"varint,4,opt,name=offset,proto3" json:"offset,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetChatsByUserRequest) Reset() {
	*x = GetChatsByUserRequest{}
	mi := &file_database_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetChatsByUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetChatsByUserRequest) ProtoMessage() {}

func (x *GetChatsByUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_database_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetChatsByUserRequest.ProtoReflect.Descriptor instead.
func (*GetChatsByUserRequest) Descriptor() ([]byte, []int) {
	return file_database_proto_rawDescGZIP(), []int{24}
}

func (x *GetChatsByUserRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *GetChatsByUserRequest) GetAssistantId() string {
	if x != nil {
		return x.AssistantId
	}
	return ""
}

func (x *GetChatsByUserRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *GetChatsByUserRequest) GetOffset() int32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

type ChatsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Chats         []*ChatResponse        `protobuf:"bytes,1,rep,name=chats,proto3" json:"chats,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChatsResponse) Reset() {
	*x = ChatsResponse{}
	mi := &file_database_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChatsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatsResponse) ProtoMessage() {}

func (x *ChatsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_database_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChatsResponse.ProtoReflect.Descriptor instead.
func (*ChatsResponse) Descriptor() ([]byte, []int) {
	return file_database_proto_rawDescGZIP(), []int{25}
}

func (x *ChatsResponse) GetChats() []*ChatResponse {
	if x != nil {
		return x.Chats
	}
	return nil
}

type UpdateChatRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	AssistantId   string                 `protobuf:"bytes,2,opt,name=assistant_id,json=assistantId,proto3" json:"assistant_id,omitempty"`
	CustomerId    string                 `protobuf:"bytes,3,opt,name=customer_id,json=customerId,proto3" json:"customer_id,omitempty"`
	Platform      string                 `protobuf:"bytes,4,opt,name=platform,proto3" json:"platform,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateChatRequest) Reset() {
	*x = UpdateChatRequest{}
	mi := &file_database_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateChatRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateChatRequest) ProtoMessage() {}

func (x *UpdateChatRequest) ProtoReflect() protoreflect.Message {
	mi := &file_database_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateChatRequest.ProtoReflect.Descriptor instead.
func (*UpdateChatRequest) Descriptor() ([]byte, []int) {
	return file_database_proto_rawDescGZIP(), []int{26}
}

func (x *UpdateChatRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdateChatRequest) GetAssistantId() string {
	if x != nil {
		return x.AssistantId
	}
	return ""
}

func (x *UpdateChatRequest) GetCustomerId() string {
	if x != nil {
		return x.CustomerId
	}
	return ""
}

func (x *UpdateChatRequest) GetPlatform() string {
	if x != nil {
		return x.Platform
	}
	return ""
}

type DeleteChatRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteChatRequest) Reset() {
	*x = DeleteChatRequest{}
	mi := &file_database_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteChatRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteChatRequest) ProtoMessage() {}

func (x *DeleteChatRequest) ProtoReflect() protoreflect.Message {
	mi := &file_database_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteChatRequest.ProtoReflect.Descriptor instead.
func (*DeleteChatRequest) Descriptor() ([]byte, []int) {
	return file_database_proto_rawDescGZIP(), []int{27}
}

func (x *DeleteChatRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type DeleteChatResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteChatResponse) Reset() {
	*x = DeleteChatResponse{}
	mi := &file_database_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteChatResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteChatResponse) ProtoMessage() {}

func (x *DeleteChatResponse) ProtoReflect() protoreflect.Message {
	mi := &file_database_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteChatResponse.ProtoReflect.Descriptor instead.
func (*DeleteChatResponse) Descriptor() ([]byte, []int) {
	return file_database_proto_rawDescGZIP(), []int{28}
}

func (x *DeleteChatResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type UpdateMessageRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	ChatId        string                 `protobuf:"bytes,2,opt,name=chat_id,json=chatId,proto3" json:"chat_id,omitempty"`
	Role          string                 `protobuf:"bytes,3,opt,name=role,proto3" json:"role,omitempty"`
	Content       string                 `protobuf:"bytes,4,opt,name=content,proto3" json:"content,omitempty"`
	Platform      string                 `protobuf:"bytes,5,opt,name=platform,proto3" json:"platform,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateMessageRequest) Reset() {
	*x = UpdateMessageRequest{}
	mi := &file_database_proto_msgTypes[29]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateMessageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateMessageRequest) ProtoMessage() {}

func (x *UpdateMessageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_database_proto_msgTypes[29]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateMessageRequest.ProtoReflect.Descriptor instead.
func (*UpdateMessageRequest) Descriptor() ([]byte, []int) {
	return file_database_proto_rawDescGZIP(), []int{29}
}

func (x *UpdateMessageRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdateMessageRequest) GetChatId() string {
	if x != nil {
		return x.ChatId
	}
	return ""
}

func (x *UpdateMessageRequest) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

func (x *UpdateMessageRequest) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *UpdateMessageRequest) GetPlatform() string {
	if x != nil {
		return x.Platform
	}
	return ""
}

type DeleteMessageRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteMessageRequest) Reset() {
	*x = DeleteMessageRequest{}
	mi := &file_database_proto_msgTypes[30]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteMessageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteMessageRequest) ProtoMessage() {}

func (x *DeleteMessageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_database_proto_msgTypes[30]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteMessageRequest.ProtoReflect.Descriptor instead.
func (*DeleteMessageRequest) Descriptor() ([]byte, []int) {
	return file_database_proto_rawDescGZIP(), []int{30}
}

func (x *DeleteMessageRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type DeleteMessageResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteMessageResponse) Reset() {
	*x = DeleteMessageResponse{}
	mi := &file_database_proto_msgTypes[31]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteMessageResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteMessageResponse) ProtoMessage() {}

func (x *DeleteMessageResponse) ProtoReflect() protoreflect.Message {
	mi := &file_database_proto_msgTypes[31]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteMessageResponse.ProtoReflect.Descriptor instead.
func (*DeleteMessageResponse) Descriptor() ([]byte, []int) {
	return file_database_proto_rawDescGZIP(), []int{31}
}

func (x *DeleteMessageResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type GetChatPagesCountRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AssistantId   string                 `protobuf:"bytes,1,opt,name=assistant_id,json=assistantId,proto3" json:"assistant_id,omitempty"`
	ChatsPerPage  int32                  `protobuf:"varint,2,opt,name=chats_per_page,json=chatsPerPage,proto3" json:"chats_per_page,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetChatPagesCountRequest) Reset() {
	*x = GetChatPagesCountRequest{}
	mi := &file_database_proto_msgTypes[32]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetChatPagesCountRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetChatPagesCountRequest) ProtoMessage() {}

func (x *GetChatPagesCountRequest) ProtoReflect() protoreflect.Message {
	mi := &file_database_proto_msgTypes[32]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetChatPagesCountRequest.ProtoReflect.Descriptor instead.
func (*GetChatPagesCountRequest) Descriptor() ([]byte, []int) {
	return file_database_proto_rawDescGZIP(), []int{32}
}

func (x *GetChatPagesCountRequest) GetAssistantId() string {
	if x != nil {
		return x.AssistantId
	}
	return ""
}

func (x *GetChatPagesCountRequest) GetChatsPerPage() int32 {
	if x != nil {
		return x.ChatsPerPage
	}
	return 0
}

type ChatPagesCountResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PagesCount    int32                  `protobuf:"varint,1,opt,name=pages_count,json=pagesCount,proto3" json:"pages_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChatPagesCountResponse) Reset() {
	*x = ChatPagesCountResponse{}
	mi := &file_database_proto_msgTypes[33]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChatPagesCountResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatPagesCountResponse) ProtoMessage() {}

func (x *ChatPagesCountResponse) ProtoReflect() protoreflect.Message {
	mi := &file_database_proto_msgTypes[33]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChatPagesCountResponse.ProtoReflect.Descriptor instead.
func (*ChatPagesCountResponse) Descriptor() ([]byte, []int) {
	return file_database_proto_rawDescGZIP(), []int{33}
}

func (x *ChatPagesCountResponse) GetPagesCount() int32 {
	if x != nil {
		return x.PagesCount
	}
	return 0
}

type GetChatPageRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AssistantId   string                 `protobuf:"bytes,1,opt,name=assistant_id,json=assistantId,proto3" json:"assistant_id,omitempty"`
	Page          int32                  `protobuf:"varint,2,opt,name=page,proto3" json:"page,omitempty"`
	ChatsPerPage  int32                  `protobuf:"varint,3,opt,name=chats_per_page,json=chatsPerPage,proto3" json:"chats_per_page,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetChatPageRequest) Reset() {
	*x = GetChatPageRequest{}
	mi := &file_database_proto_msgTypes[34]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetChatPageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetChatPageRequest) ProtoMessage() {}

func (x *GetChatPageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_database_proto_msgTypes[34]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetChatPageRequest.ProtoReflect.Descriptor instead.
func (*GetChatPageRequest) Descriptor() ([]byte, []int) {
	return file_database_proto_rawDescGZIP(), []int{34}
}

func (x *GetChatPageRequest) GetAssistantId() string {
	if x != nil {
		return x.AssistantId
	}
	return ""
}

func (x *GetChatPageRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *GetChatPageRequest) GetChatsPerPage() int32 {
	if x != nil {
		return x.ChatsPerPage
	}
	return 0
}

type SearchChatsByUserRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AssistantId   string                 `protobuf:"bytes,1,opt,name=assistant_id,json=assistantId,proto3" json:"assistant_id,omitempty"`
	Search        string                 `protobuf:"bytes,2,opt,name=search,proto3" json:"search,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchChatsByUserRequest) Reset() {
	*x = SearchChatsByUserRequest{}
	mi := &file_database_proto_msgTypes[35]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchChatsByUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchChatsByUserRequest) ProtoMessage() {}

func (x *SearchChatsByUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_database_proto_msgTypes[35]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchChatsByUserRequest.ProtoReflect.Descriptor instead.
func (*SearchChatsByUserRequest) Descriptor() ([]byte, []int) {
	return file_database_proto_rawDescGZIP(), []int{35}
}

func (x *SearchChatsByUserRequest) GetAssistantId() string {
	if x != nil {
		return x.AssistantId
	}
	return ""
}

func (x *SearchChatsByUserRequest) GetSearch() string {
	if x != nil {
		return x.Search
	}
	return ""
}

type SearchChatsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Chats         []*ChatResponse        `protobuf:"bytes,1,rep,name=chats,proto3" json:"chats,omitempty"`
	TotalCount    int32                  `protobuf:"varint,2,opt,name=total_count,json=totalCount,proto3" json:"total_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchChatsResponse) Reset() {
	*x = SearchChatsResponse{}
	mi := &file_database_proto_msgTypes[36]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchChatsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchChatsResponse) ProtoMessage() {}

func (x *SearchChatsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_database_proto_msgTypes[36]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchChatsResponse.ProtoReflect.Descriptor instead.
func (*SearchChatsResponse) Descriptor() ([]byte, []int) {
	return file_database_proto_rawDescGZIP(), []int{36}
}

func (x *SearchChatsResponse) GetChats() []*ChatResponse {
	if x != nil {
		return x.Chats
	}
	return nil
}

func (x *SearchChatsResponse) GetTotalCount() int32 {
	if x != nil {
		return x.TotalCount
	}
	return 0
}

type CreateAssistantRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	BotToken      string                 `protobuf:"bytes,2,opt,name=bot_token,json=botToken,proto3" json:"bot_token,omitempty"`
	ApiToken      string                 `protobuf:"bytes,3,opt,name=api_token,json=apiToken,proto3" json:"api_token,omitempty"`
	UserId        string                 `protobuf:"bytes,4,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateAssistantRequest) Reset() {
	*x = CreateAssistantRequest{}
	mi := &file_database_proto_msgTypes[37]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateAssistantRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateAssistantRequest) ProtoMessage() {}

func (x *CreateAssistantRequest) ProtoReflect() protoreflect.Message {
	mi := &file_database_proto_msgTypes[37]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateAssistantRequest.ProtoReflect.Descriptor instead.
func (*CreateAssistantRequest) Descriptor() ([]byte, []int) {
	return file_database_proto_rawDescGZIP(), []int{37}
}

func (x *CreateAssistantRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateAssistantRequest) GetBotToken() string {
	if x != nil {
		return x.BotToken
	}
	return ""
}

func (x *CreateAssistantRequest) GetApiToken() string {
	if x != nil {
		return x.ApiToken
	}
	return ""
}

func (x *CreateAssistantRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type AssistantResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	BotToken      string                 `protobuf:"bytes,3,opt,name=bot_token,json=botToken,proto3" json:"bot_token,omitempty"`
	ApiToken      string                 `protobuf:"bytes,4,opt,name=api_token,json=apiToken,proto3" json:"api_token,omitempty"`
	UserId        string                 `protobuf:"bytes,5,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,6,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     string                 `protobuf:"bytes,7,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AssistantResponse) Reset() {
	*x = AssistantResponse{}
	mi := &file_database_proto_msgTypes[38]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AssistantResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AssistantResponse) ProtoMessage() {}

func (x *AssistantResponse) ProtoReflect() protoreflect.Message {
	mi := &file_database_proto_msgTypes[38]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AssistantResponse.ProtoReflect.Descriptor instead.
func (*AssistantResponse) Descriptor() ([]byte, []int) {
	return file_database_proto_rawDescGZIP(), []int{38}
}

func (x *AssistantResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *AssistantResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *AssistantResponse) GetBotToken() string {
	if x != nil {
		return x.BotToken
	}
	return ""
}

func (x *AssistantResponse) GetApiToken() string {
	if x != nil {
		return x.ApiToken
	}
	return ""
}

func (x *AssistantResponse) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *AssistantResponse) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *AssistantResponse) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

type GetAssistantRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAssistantRequest) Reset() {
	*x = GetAssistantRequest{}
	mi := &file_database_proto_msgTypes[39]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAssistantRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAssistantRequest) ProtoMessage() {}

func (x *GetAssistantRequest) ProtoReflect() protoreflect.Message {
	mi := &file_database_proto_msgTypes[39]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAssistantRequest.ProtoReflect.Descriptor instead.
func (*GetAssistantRequest) Descriptor() ([]byte, []int) {
	return file_database_proto_rawDescGZIP(), []int{39}
}

func (x *GetAssistantRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetAssistantByAPITokenRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ApiToken      string                 `protobuf:"bytes,1,opt,name=api_token,json=apiToken,proto3" json:"api_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAssistantByAPITokenRequest) Reset() {
	*x = GetAssistantByAPITokenRequest{}
	mi := &file_database_proto_msgTypes[40]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAssistantByAPITokenRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAssistantByAPITokenRequest) ProtoMessage() {}

func (x *GetAssistantByAPITokenRequest) ProtoReflect() protoreflect.Message {
	mi := &file_database_proto_msgTypes[40]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAssistantByAPITokenRequest.ProtoReflect.Descriptor instead.
func (*GetAssistantByAPITokenRequest) Descriptor() ([]byte, []int) {
	return file_database_proto_rawDescGZIP(), []int{40}
}

func (x *GetAssistantByAPITokenRequest) GetApiToken() string {
	if x != nil {
		return x.ApiToken
	}
	return ""
}

type UpdateAssistantRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	BotToken      string                 `protobuf:"bytes,3,opt,name=bot_token,json=botToken,proto3" json:"bot_token,omitempty"`
	ApiToken      string                 `protobuf:"bytes,4,opt,name=api_token,json=apiToken,proto3" json:"api_token,omitempty"`
	UserId        string                 `protobuf:"bytes,5,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateAssistantRequest) Reset() {
	*x = UpdateAssistantRequest{}
	mi := &file_database_proto_msgTypes[41]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateAssistantRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateAssistantRequest) ProtoMessage() {}

func (x *UpdateAssistantRequest) ProtoReflect() protoreflect.Message {
	mi := &file_database_proto_msgTypes[41]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateAssistantRequest.ProtoReflect.Descriptor instead.
func (*UpdateAssistantRequest) Descriptor() ([]byte, []int) {
	return file_database_proto_rawDescGZIP(), []int{41}
}

func (x *UpdateAssistantRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdateAssistantRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UpdateAssistantRequest) GetBotToken() string {
	if x != nil {
		return x.BotToken
	}
	return ""
}

func (x *UpdateAssistantRequest) GetApiToken() string {
	if x != nil {
		return x.ApiToken
	}
	return ""
}

func (x *UpdateAssistantRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type DeleteAssistantRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteAssistantRequest) Reset() {
	*x = DeleteAssistantRequest{}
	mi := &file_database_proto_msgTypes[42]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteAssistantRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteAssistantRequest) ProtoMessage() {}

func (x *DeleteAssistantRequest) ProtoReflect() protoreflect.Message {
	mi := &file_database_proto_msgTypes[42]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteAssistantRequest.ProtoReflect.Descriptor instead.
func (*DeleteAssistantRequest) Descriptor() ([]byte, []int) {
	return file_database_proto_rawDescGZIP(), []int{42}
}

func (x *DeleteAssistantRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type DeleteAssistantResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteAssistantResponse) Reset() {
	*x = DeleteAssistantResponse{}
	mi := &file_database_proto_msgTypes[43]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteAssistantResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteAssistantResponse) ProtoMessage() {}

func (x *DeleteAssistantResponse) ProtoReflect() protoreflect.Message {
	mi := &file_database_proto_msgTypes[43]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteAssistantResponse.ProtoReflect.Descriptor instead.
func (*DeleteAssistantResponse) Descriptor() ([]byte, []int) {
	return file_database_proto_rawDescGZIP(), []int{43}
}

func (x *DeleteAssistantResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

var File_database_proto protoreflect.FileDescriptor

const file_database_proto_rawDesc = "" +
	"\n" +
	"\x0edatabase.proto\x12\bdatabase\"\x8b\x01\n" +
	"\x10AnalyticsRequest\x12!\n" +
	"\fassistant_id\x18\x01 \x01(\tR\vassistantId\x12\x1a\n" +
	"\bplatform\x18\x02 \x01(\tR\bplatform\x12\x1d\n" +
	"\n" +
	"start_date\x18\x03 \x01(\tR\tstartDate\x12\x19\n" +
	"\bend_date\x18\x04 \x01(\tR\aendDate\"\x96\x01\n" +
	"\x1bAnalyticsByAssistantRequest\x12!\n" +
	"\fassistant_id\x18\x01 \x01(\tR\vassistantId\x12\x1a\n" +
	"\bplatform\x18\x02 \x01(\tR\bplatform\x12\x1d\n" +
	"\n" +
	"start_date\x18\x03 \x01(\tR\tstartDate\x12\x19\n" +
	"\bend_date\x18\x04 \x01(\tR\aendDate\"\xa3\x01\n" +
	"\x11AnalyticsResponse\x12!\n" +
	"\fassistant_id\x18\x01 \x01(\tR\vassistantId\x12\x1f\n" +
	"\vtotal_chats\x18\x02 \x01(\x05R\n" +
	"totalChats\x12!\n" +
	"\factive_users\x18\x03 \x01(\x05R\vactiveUsers\x12'\n" +
	"\x0fengagement_rate\x18\x04 \x01(\x01R\x0eengagementRate\"b\n" +
	"\x11CreateUserRequest\x12\x14\n" +
	"\x05email\x18\x01 \x01(\tR\x05email\x12#\n" +
	"\rpassword_hash\x18\x02 \x01(\tR\fpasswordHash\x12\x12\n" +
	"\x04role\x18\x03 \x01(\tR\x04role\" \n" +
	"\x0eGetUserRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"\x8c\x01\n" +
	"\fUserResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05email\x18\x02 \x01(\tR\x05email\x12#\n" +
	"\rpassword_hash\x18\x03 \x01(\tR\fpasswordHash\x12\x12\n" +
	"\x04role\x18\x04 \x01(\tR\x04role\x12\x1d\n" +
	"\n" +
	"created_at\x18\x05 \x01(\tR\tcreatedAt\"p\n" +
	"\x17SaveRefreshTokenRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x1d\n" +
	"\n" +
	"token_hash\x18\x02 \x01(\tR\ttokenHash\x12\x1d\n" +
	"\n" +
	"expires_at\x18\x03 \x01(\tR\texpiresAt\"4\n" +
	"\x18SaveRefreshTokenResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"7\n" +
	"\x16GetRefreshTokenRequest\x12\x1d\n" +
	"\n" +
	"token_hash\x18\x01 \x01(\tR\ttokenHash\"\x9c\x01\n" +
	"\x14RefreshTokenResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x1d\n" +
	"\n" +
	"token_hash\x18\x03 \x01(\tR\ttokenHash\x12\x1d\n" +
	"\n" +
	"expires_at\x18\x04 \x01(\tR\texpiresAt\x12\x1d\n" +
	"\n" +
	"created_at\x18\x05 \x01(\tR\tcreatedAt\":\n" +
	"\x19DeleteRefreshTokenRequest\x12\x1d\n" +
	"\n" +
	"token_hash\x18\x01 \x01(\tR\ttokenHash\"6\n" +
	"\x1aDeleteRefreshTokenResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"s\n" +
	"\x11CreateChatRequest\x12!\n" +
	"\fassistant_id\x18\x01 \x01(\tR\vassistantId\x12\x1f\n" +
	"\vcustomer_id\x18\x02 \x01(\tR\n" +
	"customerId\x12\x1a\n" +
	"\bplatform\x18\x03 \x01(\tR\bplatform\"\xe1\x01\n" +
	"\fChatResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12!\n" +
	"\fassistant_id\x18\x02 \x01(\tR\vassistantId\x12\x1f\n" +
	"\vcustomer_id\x18\x03 \x01(\tR\n" +
	"customerId\x12\x1a\n" +
	"\bplatform\x18\x04 \x01(\tR\bplatform\x12\x1d\n" +
	"\n" +
	"created_at\x18\x05 \x01(\tR\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\x06 \x01(\tR\tupdatedAt\x12#\n" +
	"\rmessage_count\x18\a \x01(\x05R\fmessageCount\"w\n" +
	"\x12SaveMessageRequest\x12\x17\n" +
	"\achat_id\x18\x01 \x01(\tR\x06chatId\x12\x12\n" +
	"\x04role\x18\x02 \x01(\tR\x04role\x12\x18\n" +
	"\acontent\x18\x03 \x01(\tR\acontent\x12\x1a\n" +
	"\bplatform\x18\x04 \x01(\tR\bplatform\"\xa3\x01\n" +
	"\x0fMessageResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x17\n" +
	"\achat_id\x18\x02 \x01(\tR\x06chatId\x12\x12\n" +
	"\x04role\x18\x03 \x01(\tR\x04role\x12\x18\n" +
	"\acontent\x18\x04 \x01(\tR\acontent\x12\x1a\n" +
	"\bplatform\x18\x05 \x01(\tR\bplatform\x12\x1d\n" +
	"\n" +
	"created_at\x18\x06 \x01(\tR\tcreatedAt\"_\n" +
	"\x16GetChatMessagesRequest\x12\x17\n" +
	"\achat_id\x18\x01 \x01(\tR\x06chatId\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\x05R\x05limit\x12\x16\n" +
	"\x06offset\x18\x03 \x01(\x05R\x06offset\"4\n" +
	"\x19GetAllChatMessagesRequest\x12\x17\n" +
	"\achat_id\x18\x01 \x01(\tR\x06chatId\"I\n" +
	"\x10MessagesResponse\x125\n" +
	"\bmessages\x18\x01 \x03(\v2\x19.database.MessageResponseR\bmessages\"-\n" +
	"\x15GetUserByEmailRequest\x12\x14\n" +
	"\x05email\x18\x01 \x01(\tR\x05email\"r\n" +
	"\x11UpdateUserRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05email\x18\x02 \x01(\tR\x05email\x12#\n" +
	"\rpassword_hash\x18\x03 \x01(\tR\fpasswordHash\x12\x12\n" +
	"\x04role\x18\x04 \x01(\tR\x04role\"#\n" +
	"\x11DeleteUserRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\".\n" +
	"\x12DeleteUserResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\" \n" +
	"\x0eGetChatRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"\x81\x01\n" +
	"\x15GetChatsByUserRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12!\n" +
	"\fassistant_id\x18\x02 \x01(\tR\vassistantId\x12\x14\n" +
	"\x05limit\x18\x03 \x01(\x05R\x05limit\x12\x16\n" +
	"\x06offset\x18\x04 \x01(\x05R\x06offset\"=\n" +
	"\rChatsResponse\x12,\n" +
	"\x05chats\x18\x01 \x03(\v2\x16.database.ChatResponseR\x05chats\"\x83\x01\n" +
	"\x11UpdateChatRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12!\n" +
	"\fassistant_id\x18\x02 \x01(\tR\vassistantId\x12\x1f\n" +
	"\vcustomer_id\x18\x03 \x01(\tR\n" +
	"customerId\x12\x1a\n" +
	"\bplatform\x18\x04 \x01(\tR\bplatform\"#\n" +
	"\x11DeleteChatRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\".\n" +
	"\x12DeleteChatResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"\x89\x01\n" +
	"\x14UpdateMessageRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x17\n" +
	"\achat_id\x18\x02 \x01(\tR\x06chatId\x12\x12\n" +
	"\x04role\x18\x03 \x01(\tR\x04role\x12\x18\n" +
	"\acontent\x18\x04 \x01(\tR\acontent\x12\x1a\n" +
	"\bplatform\x18\x05 \x01(\tR\bplatform\"&\n" +
	"\x14DeleteMessageRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"1\n" +
	"\x15DeleteMessageResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"c\n" +
	"\x18GetChatPagesCountRequest\x12!\n" +
	"\fassistant_id\x18\x01 \x01(\tR\vassistantId\x12$\n" +
	"\x0echats_per_page\x18\x02 \x01(\x05R\fchatsPerPage\"9\n" +
	"\x16ChatPagesCountResponse\x12\x1f\n" +
	"\vpages_count\x18\x01 \x01(\x05R\n" +
	"pagesCount\"q\n" +
	"\x12GetChatPageRequest\x12!\n" +
	"\fassistant_id\x18\x01 \x01(\tR\vassistantId\x12\x12\n" +
	"\x04page\x18\x02 \x01(\x05R\x04page\x12$\n" +
	"\x0echats_per_page\x18\x03 \x01(\x05R\fchatsPerPage\"U\n" +
	"\x18SearchChatsByUserRequest\x12!\n" +
	"\fassistant_id\x18\x01 \x01(\tR\vassistantId\x12\x16\n" +
	"\x06search\x18\x02 \x01(\tR\x06search\"d\n" +
	"\x13SearchChatsResponse\x12,\n" +
	"\x05chats\x18\x01 \x03(\v2\x16.database.ChatResponseR\x05chats\x12\x1f\n" +
	"\vtotal_count\x18\x02 \x01(\x05R\n" +
	"totalCount\"\x7f\n" +
	"\x16CreateAssistantRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x1b\n" +
	"\tbot_token\x18\x02 \x01(\tR\bbotToken\x12\x1b\n" +
	"\tapi_token\x18\x03 \x01(\tR\bapiToken\x12\x17\n" +
	"\auser_id\x18\x04 \x01(\tR\x06userId\"\xc8\x01\n" +
	"\x11AssistantResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x1b\n" +
	"\tbot_token\x18\x03 \x01(\tR\bbotToken\x12\x1b\n" +
	"\tapi_token\x18\x04 \x01(\tR\bapiToken\x12\x17\n" +
	"\auser_id\x18\x05 \x01(\tR\x06userId\x12\x1d\n" +
	"\n" +
	"created_at\x18\x06 \x01(\tR\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\a \x01(\tR\tupdatedAt\"%\n" +
	"\x13GetAssistantRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"<\n" +
	"\x1dGetAssistantByAPITokenRequest\x12\x1b\n" +
	"\tapi_token\x18\x01 \x01(\tR\bapiToken\"\x8f\x01\n" +
	"\x16UpdateAssistantRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x1b\n" +
	"\tbot_token\x18\x03 \x01(\tR\bbotToken\x12\x1b\n" +
	"\tapi_token\x18\x04 \x01(\tR\bapiToken\x12\x17\n" +
	"\auser_id\x18\x05 \x01(\tR\x06userId\"(\n" +
	"\x16DeleteAssistantRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"3\n" +
	"\x17DeleteAssistantResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess2\xa8\x11\n" +
	"\x0fDatabaseService\x12G\n" +
	"\fGetAnalytics\x12\x1a.database.AnalyticsRequest\x1a\x1b.database.AnalyticsResponse\x12]\n" +
	"\x17GetAnalyticsByAssistant\x12%.database.AnalyticsByAssistantRequest\x1a\x1b.database.AnalyticsResponse\x12A\n" +
	"\n" +
	"CreateUser\x12\x1b.database.CreateUserRequest\x1a\x16.database.UserResponse\x12;\n" +
	"\aGetUser\x12\x18.database.GetUserRequest\x1a\x16.database.UserResponse\x12I\n" +
	"\x0eGetUserByEmail\x12\x1f.database.GetUserByEmailRequest\x1a\x16.database.UserResponse\x12A\n" +
	"\n" +
	"UpdateUser\x12\x1b.database.UpdateUserRequest\x1a\x16.database.UserResponse\x12G\n" +
	"\n" +
	"DeleteUser\x12\x1b.database.DeleteUserRequest\x1a\x1c.database.DeleteUserResponse\x12Y\n" +
	"\x10SaveRefreshToken\x12!.database.SaveRefreshTokenRequest\x1a\".database.SaveRefreshTokenResponse\x12S\n" +
	"\x0fGetRefreshToken\x12 .database.GetRefreshTokenRequest\x1a\x1e.database.RefreshTokenResponse\x12_\n" +
	"\x12DeleteRefreshToken\x12#.database.DeleteRefreshTokenRequest\x1a$.database.DeleteRefreshTokenResponse\x12P\n" +
	"\x0fCreateAssistant\x12 .database.CreateAssistantRequest\x1a\x1b.database.AssistantResponse\x12J\n" +
	"\fGetAssistant\x12\x1d.database.GetAssistantRequest\x1a\x1b.database.AssistantResponse\x12^\n" +
	"\x16GetAssistantByAPIToken\x12'.database.GetAssistantByAPITokenRequest\x1a\x1b.database.AssistantResponse\x12P\n" +
	"\x0fUpdateAssistant\x12 .database.UpdateAssistantRequest\x1a\x1b.database.AssistantResponse\x12V\n" +
	"\x0fDeleteAssistant\x12 .database.DeleteAssistantRequest\x1a!.database.DeleteAssistantResponse\x12A\n" +
	"\n" +
	"CreateChat\x12\x1b.database.CreateChatRequest\x1a\x16.database.ChatResponse\x12;\n" +
	"\aGetChat\x12\x18.database.GetChatRequest\x1a\x16.database.ChatResponse\x12J\n" +
	"\x0eGetChatsByUser\x12\x1f.database.GetChatsByUserRequest\x1a\x17.database.ChatsResponse\x12A\n" +
	"\n" +
	"UpdateChat\x12\x1b.database.UpdateChatRequest\x1a\x16.database.ChatResponse\x12G\n" +
	"\n" +
	"DeleteChat\x12\x1b.database.DeleteChatRequest\x1a\x1c.database.DeleteChatResponse\x12F\n" +
	"\vSaveMessage\x12\x1c.database.SaveMessageRequest\x1a\x19.database.MessageResponse\x12O\n" +
	"\x0fGetChatMessages\x12 .database.GetChatMessagesRequest\x1a\x1a.database.MessagesResponse\x12U\n" +
	"\x12GetAllChatMessages\x12#.database.GetAllChatMessagesRequest\x1a\x1a.database.MessagesResponse\x12J\n" +
	"\rUpdateMessage\x12\x1e.database.UpdateMessageRequest\x1a\x19.database.MessageResponse\x12P\n" +
	"\rDeleteMessage\x12\x1e.database.DeleteMessageRequest\x1a\x1f.database.DeleteMessageResponse\x12Y\n" +
	"\x11GetChatPagesCount\x12\".database.GetChatPagesCountRequest\x1a .database.ChatPagesCountResponse\x12D\n" +
	"\vGetChatPage\x12\x1c.database.GetChatPageRequest\x1a\x17.database.ChatsResponse\x12V\n" +
	"\x11SearchChatsByUser\x12\".database.SearchChatsByUserRequest\x1a\x1d.database.SearchChatsResponseB+Z)diaxel_zerde/database-service/proto;protob\x06proto3"

var (
	file_database_proto_rawDescOnce sync.Once
	file_database_proto_rawDescData []byte
)

func file_database_proto_rawDescGZIP() []byte {
	file_database_proto_rawDescOnce.Do(func() {
		file_database_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_database_proto_rawDesc), len(file_database_proto_rawDesc)))
	})
	return file_database_proto_rawDescData
}

var file_database_proto_msgTypes = make([]protoimpl.MessageInfo, 44)
var file_database_proto_goTypes = []any{
	(*AnalyticsRequest)(nil),              // 0: database.AnalyticsRequest
	(*AnalyticsByAssistantRequest)(nil),   // 1: database.AnalyticsByAssistantRequest
	(*AnalyticsResponse)(nil),             // 2: database.AnalyticsResponse
	(*CreateUserRequest)(nil),             // 3: database.CreateUserRequest
	(*GetUserRequest)(nil),                // 4: database.GetUserRequest
	(*UserResponse)(nil),                  // 5: database.UserResponse
	(*SaveRefreshTokenRequest)(nil),       // 6: database.SaveRefreshTokenRequest
	(*SaveRefreshTokenResponse)(nil),      // 7: database.SaveRefreshTokenResponse
	(*GetRefreshTokenRequest)(nil),        // 8: database.GetRefreshTokenRequest
	(*RefreshTokenResponse)(nil),          // 9: database.RefreshTokenResponse
	(*DeleteRefreshTokenRequest)(nil),     // 10: database.DeleteRefreshTokenRequest
	(*DeleteRefreshTokenResponse)(nil),    // 11: database.DeleteRefreshTokenResponse
	(*CreateChatRequest)(nil),             // 12: database.CreateChatRequest
	(*ChatResponse)(nil),                  // 13: database.ChatResponse
	(*SaveMessageRequest)(nil),            // 14: database.SaveMessageRequest
	(*MessageResponse)(nil),               // 15: database.MessageResponse
	(*GetChatMessagesRequest)(nil),        // 16: database.GetChatMessagesRequest
	(*GetAllChatMessagesRequest)(nil),     // 17: database.GetAllChatMessagesRequest
	(*MessagesResponse)(nil),              // 18: database.MessagesResponse
	(*GetUserByEmailRequest)(nil),         // 19: database.GetUserByEmailRequest
	(*UpdateUserRequest)(nil),             // 20: database.UpdateUserRequest
	(*DeleteUserRequest)(nil),             // 21: database.DeleteUserRequest
	(*DeleteUserResponse)(nil),            // 22: database.DeleteUserResponse
	(*GetChatRequest)(nil),                // 23: database.GetChatRequest
	(*GetChatsByUserRequest)(nil),         // 24: database.GetChatsByUserRequest
	(*ChatsResponse)(nil),                 // 25: database.ChatsResponse
	(*UpdateChatRequest)(nil),             // 26: database.UpdateChatRequest
	(*DeleteChatRequest)(nil),             // 27: database.DeleteChatRequest
	(*DeleteChatResponse)(nil),            // 28: database.DeleteChatResponse
	(*UpdateMessageRequest)(nil),          // 29: database.UpdateMessageRequest
	(*DeleteMessageRequest)(nil),          // 30: database.DeleteMessageRequest
	(*DeleteMessageResponse)(nil),         // 31: database.DeleteMessageResponse
	(*GetChatPagesCountRequest)(nil),      // 32: database.GetChatPagesCountRequest
	(*ChatPagesCountResponse)(nil),        // 33: database.ChatPagesCountResponse
	(*GetChatPageRequest)(nil),            // 34: database.GetChatPageRequest
	(*SearchChatsByUserRequest)(nil),      // 35: database.SearchChatsByUserRequest
	(*SearchChatsResponse)(nil),           // 36: database.SearchChatsResponse
	(*CreateAssistantRequest)(nil),        // 37: database.CreateAssistantRequest
	(*AssistantResponse)(nil),             // 38: database.AssistantResponse
	(*GetAssistantRequest)(nil),           // 39: database.GetAssistantRequest
	(*GetAssistantByAPITokenRequest)(nil), // 40: database.GetAssistantByAPITokenRequest
	(*UpdateAssistantRequest)(nil),        // 41: database.UpdateAssistantRequest
	(*DeleteAssistantRequest)(nil),        // 42: database.DeleteAssistantRequest
	(*DeleteAssistantResponse)(nil),       // 43: database.DeleteAssistantResponse
}
var file_database_proto_depIdxs = []int32{
	15, // 0: database.MessagesResponse.messages:type_name -> database.MessageResponse
	13, // 1: database.ChatsResponse.chats:type_name -> database.ChatResponse
	13, // 2: database.SearchChatsResponse.chats:type_name -> database.ChatResponse
	0,  // 3: database.DatabaseService.GetAnalytics:input_type -> database.AnalyticsRequest
	1,  // 4: database.DatabaseService.GetAnalyticsByAssistant:input_type -> database.AnalyticsByAssistantRequest
	3,  // 5: database.DatabaseService.CreateUser:input_type -> database.CreateUserRequest
	4,  // 6: database.DatabaseService.GetUser:input_type -> database.GetUserRequest
	19, // 7: database.DatabaseService.GetUserByEmail:input_type -> database.GetUserByEmailRequest
	20, // 8: database.DatabaseService.UpdateUser:input_type -> database.UpdateUserRequest
	21, // 9: database.DatabaseService.DeleteUser:input_type -> database.DeleteUserRequest
	6,  // 10: database.DatabaseService.SaveRefreshToken:input_type -> database.SaveRefreshTokenRequest
	8,  // 11: database.DatabaseService.GetRefreshToken:input_type -> database.GetRefreshTokenRequest
	10, // 12: database.DatabaseService.DeleteRefreshToken:input_type -> database.DeleteRefreshTokenRequest
	37, // 13: database.DatabaseService.CreateAssistant:input_type -> database.CreateAssistantRequest
	39, // 14: database.DatabaseService.GetAssistant:input_type -> database.GetAssistantRequest
	40, // 15: database.DatabaseService.GetAssistantByAPIToken:input_type -> database.GetAssistantByAPITokenRequest
	41, // 16: database.DatabaseService.UpdateAssistant:input_type -> database.UpdateAssistantRequest
	42, // 17: database.DatabaseService.DeleteAssistant:input_type -> database.DeleteAssistantRequest
	12, // 18: database.DatabaseService.CreateChat:input_type -> database.CreateChatRequest
	23, // 19: database.DatabaseService.GetChat:input_type -> database.GetChatRequest
	24, // 20: database.DatabaseService.GetChatsByUser:input_type -> database.GetChatsByUserRequest
	26, // 21: database.DatabaseService.UpdateChat:input_type -> database.UpdateChatRequest
	27, // 22: database.DatabaseService.DeleteChat:input_type -> database.DeleteChatRequest
	14, // 23: database.DatabaseService.SaveMessage:input_type -> database.SaveMessageRequest
	16, // 24: database.DatabaseService.GetChatMessages:input_type -> database.GetChatMessagesRequest
	17, // 25: database.DatabaseService.GetAllChatMessages:input_type -> database.GetAllChatMessagesRequest
	29, // 26: database.DatabaseService.UpdateMessage:input_type -> database.UpdateMessageRequest
	30, // 27: database.DatabaseService.DeleteMessage:input_type -> database.DeleteMessageRequest
	32, // 28: database.DatabaseService.GetChatPagesCount:input_type -> database.GetChatPagesCountRequest
	34, // 29: database.DatabaseService.GetChatPage:input_type -> database.GetChatPageRequest
	35, // 30: database.DatabaseService.SearchChatsByUser:input_type -> database.SearchChatsByUserRequest
	2,  // 31: database.DatabaseService.GetAnalytics:output_type -> database.AnalyticsResponse
	2,  // 32: database.DatabaseService.GetAnalyticsByAssistant:output_type -> database.AnalyticsResponse
	5,  // 33: database.DatabaseService.CreateUser:output_type -> database.UserResponse
	5,  // 34: database.DatabaseService.GetUser:output_type -> database.UserResponse
	5,  // 35: database.DatabaseService.GetUserByEmail:output_type -> database.UserResponse
	5,  // 36: database.DatabaseService.UpdateUser:output_type -> database.UserResponse
	22, // 37: database.DatabaseService.DeleteUser:output_type -> database.DeleteUserResponse
	7,  // 38: database.DatabaseService.SaveRefreshToken:output_type -> database.SaveRefreshTokenResponse
	9,  // 39: database.DatabaseService.GetRefreshToken:output_type -> database.RefreshTokenResponse
	11, // 40: database.DatabaseService.DeleteRefreshToken:output_type -> database.DeleteRefreshTokenResponse
	38, // 41: database.DatabaseService.CreateAssistant:output_type -> database.AssistantResponse
	38, // 42: database.DatabaseService.GetAssistant:output_type -> database.AssistantResponse
	38, // 43: database.DatabaseService.GetAssistantByAPIToken:output_type -> database.AssistantResponse
	38, // 44: database.DatabaseService.UpdateAssistant:output_type -> database.AssistantResponse
	43, // 45: database.DatabaseService.DeleteAssistant:output_type -> database.DeleteAssistantResponse
	13, // 46: database.DatabaseService.CreateChat:output_type -> database.ChatResponse
	13, // 47: database.DatabaseService.GetChat:output_type -> database.ChatResponse
	25, // 48: database.DatabaseService.GetChatsByUser:output_type -> database.ChatsResponse
	13, // 49: database.DatabaseService.UpdateChat:output_type -> database.ChatResponse
	28, // 50: database.DatabaseService.DeleteChat:output_type -> database.DeleteChatResponse
	15, // 51: database.DatabaseService.SaveMessage:output_type -> database.MessageResponse
	18, // 52: database.DatabaseService.GetChatMessages:output_type -> database.MessagesResponse
	18, // 53: database.DatabaseService.GetAllChatMessages:output_type -> database.MessagesResponse
	15, // 54: database.DatabaseService.UpdateMessage:output_type -> database.MessageResponse
	31, // 55: database.DatabaseService.DeleteMessage:output_type -> database.DeleteMessageResponse
	33, // 56: database.DatabaseService.GetChatPagesCount:output_type -> database.ChatPagesCountResponse
	25, // 57: database.DatabaseService.GetChatPage:output_type -> database.ChatsResponse
	36, // 58: database.DatabaseService.SearchChatsByUser:output_type -> database.SearchChatsResponse
	31, // [31:59] is the sub-list for method output_type
	3,  // [3:31] is the sub-list for method input_type
	3,  // [3:3] is the sub-list for extension type_name
	3,  // [3:3] is the sub-list for extension extendee
	0,  // [0:3] is the sub-list for field type_name
}

func init() { file_database_proto_init() }
func file_database_proto_init() {
	if File_database_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_database_proto_rawDesc), len(file_database_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   44,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_database_proto_goTypes,
		DependencyIndexes: file_database_proto_depIdxs,
		MessageInfos:      file_database_proto_msgTypes,
	}.Build()
	File_database_proto = out.File
	file_database_proto_goTypes = nil
	file_database_proto_depIdxs = nil
}
