// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.28.3
// source: proto/database.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AnalyticsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AssistantId   string                 `protobuf:"bytes,1,opt,name=assistant_id,json=assistantId,proto3" json:"assistant_id,omitempty"`
	Platform      string                 `protobuf:"bytes,2,opt,name=platform,proto3" json:"platform,omitempty"`
	StartDate     string                 `protobuf:"bytes,3,opt,name=start_date,json=startDate,proto3" json:"start_date,omitempty"`
	EndDate       string                 `protobuf:"bytes,4,opt,name=end_date,json=endDate,proto3" json:"end_date,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AnalyticsRequest) Reset() {
	*x = AnalyticsRequest{}
	mi := &file_proto_database_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AnalyticsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AnalyticsRequest) ProtoMessage() {}

func (x *AnalyticsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_database_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AnalyticsRequest.ProtoReflect.Descriptor instead.
func (*AnalyticsRequest) Descriptor() ([]byte, []int) {
	return file_proto_database_proto_rawDescGZIP(), []int{0}
}

func (x *AnalyticsRequest) GetAssistantId() string {
	if x != nil {
		return x.AssistantId
	}
	return ""
}

func (x *AnalyticsRequest) GetPlatform() string {
	if x != nil {
		return x.Platform
	}
	return ""
}

func (x *AnalyticsRequest) GetStartDate() string {
	if x != nil {
		return x.StartDate
	}
	return ""
}

func (x *AnalyticsRequest) GetEndDate() string {
	if x != nil {
		return x.EndDate
	}
	return ""
}

type AnalyticsByAssistantRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AssistantId   string                 `protobuf:"bytes,1,opt,name=assistant_id,json=assistantId,proto3" json:"assistant_id,omitempty"`
	Platform      string                 `protobuf:"bytes,2,opt,name=platform,proto3" json:"platform,omitempty"`
	StartDate     string                 `protobuf:"bytes,3,opt,name=start_date,json=startDate,proto3" json:"start_date,omitempty"`
	EndDate       string                 `protobuf:"bytes,4,opt,name=end_date,json=endDate,proto3" json:"end_date,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AnalyticsByAssistantRequest) Reset() {
	*x = AnalyticsByAssistantRequest{}
	mi := &file_proto_database_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AnalyticsByAssistantRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AnalyticsByAssistantRequest) ProtoMessage() {}

func (x *AnalyticsByAssistantRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_database_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AnalyticsByAssistantRequest.ProtoReflect.Descriptor instead.
func (*AnalyticsByAssistantRequest) Descriptor() ([]byte, []int) {
	return file_proto_database_proto_rawDescGZIP(), []int{1}
}

func (x *AnalyticsByAssistantRequest) GetAssistantId() string {
	if x != nil {
		return x.AssistantId
	}
	return ""
}

func (x *AnalyticsByAssistantRequest) GetPlatform() string {
	if x != nil {
		return x.Platform
	}
	return ""
}

func (x *AnalyticsByAssistantRequest) GetStartDate() string {
	if x != nil {
		return x.StartDate
	}
	return ""
}

func (x *AnalyticsByAssistantRequest) GetEndDate() string {
	if x != nil {
		return x.EndDate
	}
	return ""
}

type AnalyticsResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	AssistantId    string                 `protobuf:"bytes,1,opt,name=assistant_id,json=assistantId,proto3" json:"assistant_id,omitempty"`
	TotalChats     int32                  `protobuf:"varint,2,opt,name=total_chats,json=totalChats,proto3" json:"total_chats,omitempty"`
	ActiveUsers    int32                  `protobuf:"varint,3,opt,name=active_users,json=activeUsers,proto3" json:"active_users,omitempty"`
	EngagementRate float64                `protobuf:"fixed64,4,opt,name=engagement_rate,json=engagementRate,proto3" json:"engagement_rate,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *AnalyticsResponse) Reset() {
	*x = AnalyticsResponse{}
	mi := &file_proto_database_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AnalyticsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AnalyticsResponse) ProtoMessage() {}

func (x *AnalyticsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_database_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AnalyticsResponse.ProtoReflect.Descriptor instead.
func (*AnalyticsResponse) Descriptor() ([]byte, []int) {
	return file_proto_database_proto_rawDescGZIP(), []int{2}
}

func (x *AnalyticsResponse) GetAssistantId() string {
	if x != nil {
		return x.AssistantId
	}
	return ""
}

func (x *AnalyticsResponse) GetTotalChats() int32 {
	if x != nil {
		return x.TotalChats
	}
	return 0
}

func (x *AnalyticsResponse) GetActiveUsers() int32 {
	if x != nil {
		return x.ActiveUsers
	}
	return 0
}

func (x *AnalyticsResponse) GetEngagementRate() float64 {
	if x != nil {
		return x.EngagementRate
	}
	return 0
}

var File_proto_database_proto protoreflect.FileDescriptor

const file_proto_database_proto_rawDesc = "" +
	"\n" +
	"\x14proto/database.proto\x12\bdatabase\"\x8b\x01\n" +
	"\x10AnalyticsRequest\x12!\n" +
	"\fassistant_id\x18\x01 \x01(\tR\vassistantId\x12\x1a\n" +
	"\bplatform\x18\x02 \x01(\tR\bplatform\x12\x1d\n" +
	"\n" +
	"start_date\x18\x03 \x01(\tR\tstartDate\x12\x19\n" +
	"\bend_date\x18\x04 \x01(\tR\aendDate\"\x96\x01\n" +
	"\x1bAnalyticsByAssistantRequest\x12!\n" +
	"\fassistant_id\x18\x01 \x01(\tR\vassistantId\x12\x1a\n" +
	"\bplatform\x18\x02 \x01(\tR\bplatform\x12\x1d\n" +
	"\n" +
	"start_date\x18\x03 \x01(\tR\tstartDate\x12\x19\n" +
	"\bend_date\x18\x04 \x01(\tR\aendDate\"\xa3\x01\n" +
	"\x11AnalyticsResponse\x12!\n" +
	"\fassistant_id\x18\x01 \x01(\tR\vassistantId\x12\x1f\n" +
	"\vtotal_chats\x18\x02 \x01(\x05R\n" +
	"totalChats\x12!\n" +
	"\factive_users\x18\x03 \x01(\x05R\vactiveUsers\x12'\n" +
	"\x0fengagement_rate\x18\x04 \x01(\x01R\x0eengagementRate2\xb9\x01\n" +
	"\x0fDatabaseService\x12G\n" +
	"\fGetAnalytics\x12\x1a.database.AnalyticsRequest\x1a\x1b.database.AnalyticsResponse\x12]\n" +
	"\x17GetAnalyticsByAssistant\x12%.database.AnalyticsByAssistantRequest\x1a\x1b.database.AnalyticsResponseB=Z;github.com/tr1ki/diaxel_zerde_master/database-service/protob\x06proto3"

var (
	file_proto_database_proto_rawDescOnce sync.Once
	file_proto_database_proto_rawDescData []byte
)

func file_proto_database_proto_rawDescGZIP() []byte {
	file_proto_database_proto_rawDescOnce.Do(func() {
		file_proto_database_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_database_proto_rawDesc), len(file_proto_database_proto_rawDesc)))
	})
	return file_proto_database_proto_rawDescData
}

var file_proto_database_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_proto_database_proto_goTypes = []any{
	(*AnalyticsRequest)(nil),            // 0: database.AnalyticsRequest
	(*AnalyticsByAssistantRequest)(nil), // 1: database.AnalyticsByAssistantRequest
	(*AnalyticsResponse)(nil),           // 2: database.AnalyticsResponse
}
var file_proto_database_proto_depIdxs = []int32{
	0, // 0: database.DatabaseService.GetAnalytics:input_type -> database.AnalyticsRequest
	1, // 1: database.DatabaseService.GetAnalyticsByAssistant:input_type -> database.AnalyticsByAssistantRequest
	2, // 2: database.DatabaseService.GetAnalytics:output_type -> database.AnalyticsResponse
	2, // 3: database.DatabaseService.GetAnalyticsByAssistant:output_type -> database.AnalyticsResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_database_proto_init() }
func file_proto_database_proto_init() {
	if File_proto_database_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_database_proto_rawDesc), len(file_proto_database_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_database_proto_goTypes,
		DependencyIndexes: file_proto_database_proto_depIdxs,
		MessageInfos:      file_proto_database_proto_msgTypes,
	}.Build()
	File_proto_database_proto = out.File
	file_proto_database_proto_goTypes = nil
	file_proto_database_proto_depIdxs = nil
}
